### ISSUE TITLE
IndexError: index 3 is out of bounds for axis 0 with size 1

### ISSUE THREAD

**Issue by dongyangli-del** [Want2Vanish/FBMSNet#4]
Traceback (most recent call last):
  File "/home/geek/Workspace/BCI/Code/Decoding/FBMSNet/codes/classify/BCIC-IV-2a_fbcsp.py", line 537, in <module>
    ML_experiment.experiment()
  File "/home/geek/Workspace/BCI/Code/Decoding/FBMSNet/codes/classify/BCIC-IV-2a_fbcsp.py", line 381, in experiment
    y_train_predicted[:, j] = classifier.fit(x_features_train, np.asarray(y_train_cls, dtype=float))
  File "/home/geek/Workspace/BCI/Code/Decoding/FBMSNet/codes/classify/BCIC-IV-2a_fbcsp.py", line 25, in fit
    x_train_features_selected = self.feature_selection.fit(x_features,y_train)
  File "/home/geek/Workspace/BCI/Code/Decoding/FBMSNet/codes/classify/BCIC-IV-2a_fbcsp.py", line 40, in fit
    MI_features = self.MIBIF(x_train_features, y_train)
  File "/home/geek/Workspace/BCI/Code/Decoding/FBMSNet/codes/classify/BCIC-IV-2a_fbcsp.py", line 88, in MIBIF
    x_cls.update({i: x_features[cls_indx, :]})
IndexError: index 3 is out of bounds for axis 0 with size 1

请问这是怎么回事呀？

**Comment by dongyangli-del** [comment]
运行ho.py会报错，运行cv.py也会报错，运行BCIC-IV-2a也会报错

**Comment by lanzhen19** [comment]
> 运行ho.py会报错，运行cv.py也会报错，运行BCIC-IV-2a也会报错
您好，我碰到了跟您一样的问题，请问你解决了吗？

**Comment by Want2Vanish** [comment]
> 运行ho.py会报错，运行cv.py也会报错，运行BCIC-IV-2a也会报错
> 您好，我碰到了跟您一样的问题，请问你解决了吗？

您好，这个问题是由于生成样本数据的代码有误，请参考 Issue #1 。
